<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>

        <title>提示-煤矿考试系统</title>
        <link rel="stylesheet" type="text/css" href="{util->baseUrl}/css/style1.css" /> 
        <style type="text/css">
            .header_top                                 {ldelim}width:100%; height:80px; background:url({util->baseUrl}/img/user_top_bg.gif); clear:both;{rdelim}
            .header_top .logo                           {ldelim}width:880px; clear:both;{rdelim}
            .header_top .logo .left                     {ldelim}width:300px; height:80px; background-color:#FFFFFF; float:left;{rdelim}
            .header_top .logo .right                    {ldelim}width:550px; height:80px; float:right;{rdelim}
            .error_top                                  {ldelim}width:769px; height:26px; background:url({util->baseUrl}/img/user_reg_top.gif); clear:both;{rdelim}  
            .error_center                               {ldelim}width:769px; background:url({util->baseUrl}/img/user_reg_center.gif); clear:both;{rdelim}  
            .error_center .left                         {ldelim}position:relative; width:30%; float:left;{rdelim} 
            .error_center .right                        {ldelim}width:69%; text-align:left; line-height:30px; float:right;{rdelim} 
            .error_bottom                               {ldelim}width:769px; height:35px; background:url({util->baseUrl}/img/user_reg_bottom.gif); clear:both;{rdelim} 
            .error_errMsg                               {ldelim}width:720px; height:30px; font-size:14px; color:#0000FF; line-height:30px; background-color:#FCD9D7; border:1px dashed #FF0000; clear:both;{rdelim}
            .footer_msg                                 {ldelim}width:763px; height:31px; line-height:31px; text-align:left; background:url({util->baseUrl}/img/user_bottom_bg.gif); clear:both;{rdelim}
    
        </style>
    </head>
    <body>
        <br/><br/><br/><br/><br/><br/><br/><br/><br/>

        
        <div class="error_top"></div>
        <div class="error_center">
            <div class="left">
                <img src="{util->baseUrl}/img/mark_unlogin.gif" />
            </div>
            
            <div class="right">
                <font style="font-size:18px; color:#2BA007; font-weight:bold;"> 对不起，您浏览的网页可能已被删除或暂时不可用！</font><br/>
                您可以：<br/>
                （１）　查看网址是否正确<br/>
                （２）　浏览其他页面：<a href="{util->baseUrl}/" class="a3">首页</a>
           <br/>
           <span id="t" style="color: #FF0000; font-size:15px; font-weight:bold;">5</span>　秒钟后将重定向到编程词典网首页！
           
           
            </div>
           
            <div class="clear"></div>   
           
        </div>
        <div class="error_bottom"></div>
        
        <div class="cell_h"></div>

        <script language="javascript">
        var i=5;

        function fun(){ldelim}
             if(i==0){ldelim}
                  window.location.href="{util->baseUrl}/";
             {rdelim}else{ldelim}

             i--; 
             document.getElementById("t").innerHTML=i;
             {rdelim}
        {rdelim}
        setInterval("fun()", 1000);
        

        </script>
        
        
        
    </body>
</html>
