<!--尾部 -->
    <div class="clear"></div>
<div id="footer">
	<div class="footer_top"></div>
    <div class="clear"></div>
    <div class="footer_con">
    	<div class="footer_con_text">
        	Copyright&copy;吉林省明日科技有限公司<br /><a href="#" style="color: #093f6e">网站地图 | 友情链接 | 诚聘英才 | 合作伙伴 | 付款方式 | 联系我们 | 法律声明</a><br />公司地址：吉林省长春市东盛大街89号亚太广场C座2205室  公司邮箱：mingrisoft@mingrisoft.com  电话：0431-84978981  0431-84978982  0431-84972266
        </div>
    </div>
    <div class="clear"></div>
</div>
<div class="clear"></div>	
</div>
</body>
</html>
