<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>===煤矿考试系统===</title>
<link href="css/base.css" rel="stylesheet" type="text/css" />
<link href="css/reset.css" rel="stylesheet" type="text/css" />
<script src="Scripts/AC_RunActiveContent.js" type="text/javascript"></script>
<script src="Scripts/Effects.js" type="text/javascript"></script>
<script language="javascript">
function chksearch(form){ldelim}  
	if(form.searches.value==''){ldelim}
		alert('请输入查询关键字！');
        form.searches.focus();
        return false; 
   	{rdelim}
    return true;
{rdelim}
</script>
</head>
<body onload="MM_preloadImages('images/b1.jpg','images/b2.jpg','images/b3.jpg','images/b4.jpg','images/b5.jpg','images/b6.jpg','images/b7.jpg','images/35.jpg')">
<div id="box">
<!--头部开始 -->
<div id="top">

</div>
<!--<div id="banner"> -->
  <script type="text/javascript">
function openNewWindow(theURL,winName,features) {ldelim} //v2.0
	window.open(theURL,winName,features);
{rdelim}

//function flash1(){ldelim}
//	var flash2='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,19,0" width="1013" height="318">';
//		flash2+='<param id="swf" name="movie" value="images/meikuang.swf">';
///*				flash2+='<param id="swf" name="movie" value="images/bccd.swf?types='+m+'">';
//*/		flash2+='<param name="quality" value="high">';
//		flash2+='<param name="allScriptAccess" value="always"/>';
//		flash2+='<param name="wmode" value="transparent">';
//		flash2+='<embed src="images/meikuang.swf" width="1013" height="318" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent"></embed>';
//		flash2+='</object>';
//    document.write(flash2);
//{rdelim}
</script>
  <script type="text/javascript">
    /*flash1('明日科技');*/
	 //flash1();
</script>
<!--</div>-->
<div id="nav">
  <ul>
    <li><a href="index.php" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image2','','images/b1.jpg',1)"><img src="images/a1.gif" name="Image2" width="120" height="62" border="0" id="Image2" /></a></li>
    <li><a href="Training.php" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image3','','images/b2.jpg',1)"><img src="images/a2.jpg" name="Image3" width="120" height="62" border="0" id="Image3" /></a></li>
      <li><a href="#" onclick="openNewWindow('Special_exercises.php','','width=490,height=340')" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image5','','images/b4.jpg',1)"><img src="images/a4.jpg" name="Image5" width="120" height="62" border="0" id="Image5" /></a></li>
      <li><a href="{if $smarty.session.name == ''}# {else}Random_Answer.php{/if}"   {if $smarty.session.name == ''}onclick="openNewWindow('random_login.php','','width=490,height=340')"{/if} onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image4','','images/b3.jpg',1)"><img src="images/a3.jpg" name="Image4" width="120" height="62" border="0" id="Image4" /></a></li>
      <li><a href="#" onclick="openNewWindow('logins.php','','width=490,height=370')" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image6','','images/b5.jpg',1)"><img src="images/a5.jpg" name="Image6" width="120" height="62" border="0" id="Image6" /></a></li>
      <li><a href="#" onclick="openNewWindow('login.php','','width=490,height=370')" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image7','','images/b6.jpg',1)"><img src="images/a6.jpg" name="Image7" width="120" height="62" border="0" id="Image7" /></a></li>
    <li><a href="#" onclick="openNewWindow('search_examination.php','','width=490,height=370')" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image8','','images/b7.jpg',1)"><img src="images/a7.jpg" name="Image8" width="120" height="62" border="0" id="Image8" /></a></li>
      <li><a href="#" onclick="window.open('search_log.php')" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image9','','images/b8.jpg',1)"><img src="images/a8.jpg" name="Image9" width="120" height="62" border="0" id="Image9" /></a></li>
<!--  <li style="background-color: #f0eeef;height: 56px;"><form name="form_search" method="post" action="search_Training.php" onsubmit="return chksearch(this)" >-->
<!--          <input name="searches" class="top_right_a" type="text" />-->
<!--              <input type="image" name="submit" id="submit" src="images/2.jpg" style="padding-top: 23px;padding-left: 5px;"/>-->
<!--  </form></li>-->
  </ul>


</div>
<!--头部结束--> 
<!--内容开始 -->
<div id="con">
  <div id="con_left">
    <div class="news">
      <div class="news_bt">
        <div class="news_bt_t">
            <img src="images/4.jpg" usemap="#Map" width="325"/>
            <map name="Map" id="Map">
                <area shape="rect" coords="296,0,324,24" href="News_Bulletin.php" />
            </map>
        </div>
<!--        <div class="more"><a href="News_Bulletin.php"><img src="images/6.jpg" alt="" border="0" /></a></div>-->
      </div>
      <div class="news_con">
        <div class="news_con_c">
          <ul>
            {section name=new_id loop=$News}
            <li><img src="images/sl.png" /> <span style="padding-left: 2px;"><a href="News_Bulletin.php?news_id={$News[new_id].id}&new_bulletin=新闻" title="{$News[new_id].title}">{util->msubstr p=$News[new_id].title p1=0 p2=42 p3="..."}</a></span> </li>
            {/section}
            {section name=bul_id loop=$Bulletins}
            <li><img src="images/sl.png" /><span style="padding-left: 2px;"><a href="News_Bulletin.php?bulletin_id={$Bulletins[bul_id].id}&new_bulletin=公告" title="{$Bulletins[bul_id].title}">{util->msubstr p=$Bulletins[bul_id].title p1=0 p2=42 p3="..."}</a></span> </li>
            {/section}
          </ul>
        </div>
      </div>
    </div>
    <div class="kb">
      <div class="kb_bt">
          <img src="images/13.png" alt="" usemap="#Map3" width="325"/>
          <map name="Map" id="Map3"><area shape="rect" coords="302,4,324,25" href="Fraction.php" />
          </map>
      </div>
      <div class="news_con">
<!--        <div class="news_con_left"><img src="images/13.jpg" alt="" /></div>-->
        <div class="kb_con_c">
          <div class="kb_con_c_a">
            <div class="kb_con_c_a_bt"><ul style="text-align: left;"><li style="width: 37px;padding-left: 2px;;float: left;">名次</li><li style="width: 80px;float: left;text-align: left;text-indent: 1em;">姓名</li><li style="width: 80px;float: left;">工种</li><li style="width: 80px;float: left;text-align: center">分数</li></ul></div>
            <div class="kb_con_c_a_con">
              <ul>
                {php}$i=0;{/php}
                {section name=fra_id loop=$Fraction}
                {php}$i++;{/php}
              <li><ul><li style="width: 37px;text-indent: 1em;">{php}echo $i;{/php}</li><li style="width: 80px;text-indent: 1em;">{util->msubstr p=$Fraction[fra_id].name p1=0 p2=8 p3="..."}</li><li style="width: 80px;">{util->msubstr p=$Fraction[fra_id].typename p1=0 p2=10 p3="..."}</li><li style="width: 80px;text-align: center;">{$Fraction[fra_id].fraction}分</li></ul></li>
              {/section}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="con_right">
    <div class="pxnr">
      <div class="pxnr_bt">
        <div class="news_bt_t">
            <img src="images/23.png" alt="" usemap="#Map1" width="325"/>
            <map name="Map" id="Map1"><area shape="rect" coords="298,4,324,26" href="Training.php" />
            </map>
        </div>
      </div>
      <div class="news_con">
        <div class="news_con_c">
          <ul>
            {section name=tra_id loop=$Training}
            <li><img src="images/px.png" /><span style="padding-left: 1px;"> <a href="Training.php?know_id={$Training[tra_id].id}" title="{$Training[tra_id].title}">{util->msubstr p=$Training[tra_id].title p1=0 p2=38 p3="..."}</a></span> </li>
            {/section}
          </ul>
        </div>
      </div>
    </div>
    <div class="sg">
      <div class="kh_bt">
          <img src="images/12.png" alt="" usemap="#Map2" width="327"/>
          <map name="Map" id="Map2"><area shape="rect" coords="300,2,324,25" href="javascript:void(0)" onclick="openNewWindow('login.php','','width=490,height=370')" />
          </map>
<!--        <div class="more"><a href="#" onclick="openNewWindow('login.php','','width=490,height=370')" ><img src="images/10.jpg" alt="" border="0" /></a></div>-->
      </div>
      <div class="news_con">
        <div class="news_con_c">
          <ul>
            {section name=exa_id loop=$Examination}
            <li><img src="images/jt.png" /> <span style="padding-left: 1px;"><a href="#" onclick="openNewWindow('login.php?examid={$Examination[exa_id].id}','','width=490,height=435')" title="{$Examination[exa_id].title}">{util->msubstr p=$Examination[exa_id].title p1=0 p2=42 p3="..."}</a></span> </li>
            {/section}
          </ul>
        </div>
      </div>
    </div>
    <div class="sjwd">
      <div class="sjwd_bt">
          <img src="images/26.png" alt="" usemap="#Map4" />
          <map name="Map4" id="Map4">
              <area shape="poly" coords="665,28" href="#" /><area shape="rect" coords="639,1,664,25" href="Random_Answer.php" />
<!--        <div class="more"><a href="Random_Answer.php"><img src="images/25.jpg" alt="" border="0" /></a></div>-->
      </div>
      <div class="sjwd_con">
<!--        <div class="news_con_left"><img src="images/13.jpg" alt="" /></div>-->
        <div class="sjwd_con_c">
          <div id="Tab2">
            <div class="Menubox">
              <ul>
                {php}$i=0;{/php}
                {section name=work_id loop=$workTypes}
                {php}$i++;{/php}
                <li id="two{php}echo $i;{/php}" onmouseover="secBoard('two',{php}echo $i;{/php},10)"   class="hover"> <a href="#" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image30{php}echo $i;{/php}','','images/d{php}echo $i;{/php}.jpg',1)" title="{$workTypes[work_id].typename}" class="a12"> &nbsp;{util->msubstr p=$workTypes[work_id].typename p1=0 p2=10 p3=""}&nbsp;&nbsp;&nbsp;</a> </li>
                {/section}
              </ul>
            </div>
            <div class="Contentbox">
              <div id="con_two_1" >
                <div class="Contentbox_con">
                    {if $exam_problem1[0].content}
                  <form name="form_exams" method="post" action="" >
                    <span class="font3">{$exam_problem1[0].content}</span>
                      {if $exam_problem1[0].right_error!="" } <span class="font3">正确答案：{$exam_problem1[0].subs}&nbsp;&nbsp;&nbsp;&nbsp;您的答案：{$exam_problem1[0].sub}&nbsp;&nbsp;&nbsp;&nbsp;{$exam_problem1[0].right_error}</span>
                      <span class="font8">{else}
                    <span class="font4"> <span class="font5">
                    <input name="radio{$exam_problem1[0].id}" style="margin-top:20px; display:inline; float:left;" type="radio" value="正确" id="radio{$exam_problem1[0].id}" />
                    </span>
                      <span class="font6">正确</span>
                      <span class="font5">
                      <input name="radio{$exam_problem1[0].id}" style="margin-top:20px; display:inline; float:left;" type="radio" value="错误" id="radio{$exam_problem1[0].id}" />
                      </span>
                      <span class="font6">错误</span> </span><span class="font8"><input type="image" name="submits" id="submits" src="images/34.png" />
                    </span>{/if}
                  </form>
                    {/if}
                </div>
              </div>
              {php}$i=1;{/php}
              {section name=wor_id2 loop=$workTypes2}
              {php}$i++;{/php}
              <div id="con_two_{php}echo $i;{/php}" style="display:none" >
                <div class="Contentbox_con">
                    {if $workTypes2[wor_id2].exa_content!=''}
                  <form name="form_exam{$workTypes2[wor_id2].exa_id}" method="post" action="" >
                    <span class="font3">{$workTypes2[wor_id2].exa_content}</span>
                      {if $workTypes2[wor_id2].right_error!="" } <span class="font3">正确答案：{$workTypes2[wor_id2].subs}&nbsp;&nbsp;&nbsp;&nbsp;您的答案：{$workTypes2[wor_id2].sub}&nbsp;&nbsp;&nbsp;&nbsp;{$workTypes2[wor_id2].right_error}</span>
                      {else} <span class="font4"> <span class="font5">
                    <input name="radio{$workTypes2[wor_id2].exa_id}" style="margin-top:20px; display:inline; float:left;" type="radio" value="正确" id="radio{$workTypes2[wor_id2].exa_id}" />
                    </span> <span class="font6">正确</span> <span class="font5">
                    <input name="radio{$workTypes2[wor_id2].exa_id}" style="margin-top:20px; display:inline; float:left;" type="radio" value="错误" id="radio{$workTypes2[wor_id2].exa_id}" />
                    </span> <span class="font6">错误</span> </span>
                      <span class="font8"><input type="image" name="submits" id="submits" src="images/34.png" /></span>
                      {/if}
                  </form>
                    {/if}
                </div>
              </div>
              {/section} </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--内容结束 --> 
