<script src="Scripts/Random_Answer.js" type="text/javascript"></script>

<!--内容开始 -->
	<div id="sub">
    	<div id="sub_left">
        	<div class="left_fl">
            	<div class="left_fl_bt"><img src="images/38.jpg" alt="" /></div>
                <div class="left_fl_con">
                	<div id="PARENT">
  <ul id="left_fl_con1">
  {php}
  $i=0;
  {/php}
  {section name=type_id loop=$typeNames}
   {php} $i++; {/php}
    <li><a href="Random_Answer.php?type_id={$type_id}&exam_id={$exam_id}" onClick="DoMenu('ChildMenu{php} echo $i; {/php}')">{$typeNames[type_id].typename}</a>
      <ul id="ChildMenu{php} echo $i; {/php}" class="collapsed">
       {section name=exam_id loop=$examTypes}
        <li><a href="Random_Answer.php?type_id={$typeNames[type_id].id}&exam_id={$examTypes[exam_id].english}">{$examTypes[exam_id].chinese}</a></li>
       {/section}
      </ul>
    </li>
   {/section}
       
  </ul>
</div>
                </div>
            </div>
        </div>
        <div id="sub_right">
        <form name="form_addbccdinfo" method="post" >
      <div class="right">
        <div class="sub_c" style="padding-bottom:20px;">
          <div class="sub_c_bt" style="padding-top:12px; color:#000000; line-height:48px; font-size:48px; font-weight:bold; text-align:center;">{$pro_class}  随机问答<a name="radio"></a></div>
          <div class="k_con">
            <ul>
              <li> {php}
                $i=0;
            
                {/php}
                <p>{if $Radio==T}
              <li> <span style="width:660px; float:left; padding-left:13px; background-color:#ffffff;  color:#000000; margin-bottom:5px; display:inline; border:1px solid #19b10a; font-weight:bold;font-size: 48px;">
            随机问答： 单选题（选择一个正确答案字母）每题{$radioFraction}分</span></li>
              {section name=rad_id loop=$arrayRadio}
              <li> <span class="kt"> <span class="kt_t" style="font-size: 68px;line-height: 68px;">
                {$arrayRadio[rad_id].content}</span> </span> <span class="kt_a">
                   {if $arrayRadio[rad_id].search_list==6 } <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:2px; margin-left:2px; float:left; display:inline;" value="A" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1">A</span> <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:2px; margin-left:2px; float:left; display:inline;" value="B" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1">B</span> <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:2px; margin-left:2px; float:left; display:inline;" value="C" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1">C</span> <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:2px; margin-left:2px; float:left; display:inline;" value="D" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1">D</span><span class="kt_a_1">
                  <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:2px; margin-left:2px; float:left; display:inline;" value="E" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1">E</span> <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:2px; margin-left:2px; float:left; display:inline;" value="F" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1">F</span>
                  {elseif $arrayRadio[rad_id].search_list==5 } <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:2px; margin-left:2px; float:left; display:inline;" value="A" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1">A</span> <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:2px; margin-left:2px; float:left; display:inline;" value="B" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1">B</span> <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:2px; margin-left:2px; float:left; display:inline;" value="C" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1">C</span> <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:2px; margin-left:2px; float:left; display:inline;" value="D" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1">D</span><span class="kt_a_1">
                  <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:2px; margin-left:2px; float:left; display:inline;" value="E" id="radio{$arrayRadio[rad_id].id}">
                  </span><span class="kt_a_1">E</span>
                  {elseif $arrayRadio[rad_id].search_list==4 } <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:22px; margin-left:2px; float:left; display:inline;" value="A" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">A</span> <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:22px; margin-left:2px; float:left; display:inline;" value="B" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">B</span> <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:22px; margin-left:2px; float:left; display:inline;" value="C" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">C</span> <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:22px; margin-left:2px; float:left; display:inline;" value="D" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">D</span>
                  {elseif $arrayRadio[rad_id].search_list==3} <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:22px; margin-left:2px; float:left; display:inline;" value="A" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">A</span> <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:22px; margin-left:2px; float:left; display:inline;" value="B" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">B</span> <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:22px; margin-left:2px; float:left; display:inline;" value="C" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">C</span> {else} <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:22px; margin-left:2px; float:left; display:inline;" value="A" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">A</span> <span class="kt_a_1">
                <input type="radio" name="radio{$arrayRadio[rad_id].id}" style="margin-top:22px; margin-left:2px; float:left; display:inline;" value="B" id="radio{$arrayRadio[rad_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">B</span> {/if} </span> </li>
             {if $arrayRadio[rad_id].right_error!="" }   
                <li> <span style="width:660px; float:left; padding-left:13px;  background-color:#ffffff;  color:#000000; margin-bottom:5px; margin-top:40px;display:inline; border:1px solid #19b10a; font-weight:bold;font-size: 68px;">正确答案：{$arrayRadio[rad_id].answer}<br>您的答案：{$arrayRadio[rad_id].sub}&nbsp;&nbsp;&nbsp;&nbsp;{$arrayRadio[rad_id].right_error}</span>
                 {if $arrayRadio[rad_id].resolve!=""}
                <br>问题解析：{$arrayRadio[rad_id].resolve}
                {/if}
                </li>
              {/if}
              
              {/section}
              {/if}
              
              
              {if $Checkbox==T}
              <li> <span style="width:660px; float:left; padding-left:13px; background-color:#ffffff;  color:#000000; margin-bottom:5px; display:inline; border:1px solid #19b10a; font-weight:bold;font-size: 48px;">
              随机问答： 多选题（选择两个或两个以上正确答案字母）每题{$checkboxFraction}分</span></li>
              {section name=chk_id loop=$arrayCheckbox}
              <li> <span class="kt"> <span class="kt_t" style="font-size: 68px;line-height: 68px;">
                
                {$arrayCheckbox[chk_id].content}</span> </span> <span class="kt_a">
                  {if $arrayCheckbox[chk_id].search_list==8} <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:2px; float; display:inline;" value="A" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">A</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:2px; float; display:inline;" value="B" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1">B</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:2px; float; display:inline;" value="C" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1">C</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:2px; float; display:inline;" value="D" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1">D</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:2px; float; display:inline;" value="E" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1">E</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:2px; float; display:inline;" value="F" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1">F</span><span class="kt_a_1">
                  <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:2px; float; display:inline;" value="G" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1">G</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:2px; float; display:inline;" value="H" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1">H</span>
                  {elseif $arrayCheckbox[chk_id].search_list==7} <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:2px; float; display:inline;" value="A" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1">A</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:2px; float; display:inline;" value="B" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1">B</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:2px; float; display:inline;" value="C" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1">C</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:2px; float; display:inline;" value="D" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1">D</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:2px; float; display:inline;" value="E" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1">E</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:2px; float; display:inline;" value="F" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1">F</span><span class="kt_a_1">
                  <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:2px; float; display:inline;" value="G" id="checkbox{$arrayCheckbox[chk_id].id}">
                  </span><span class="kt_a_1">G</span>
                  {elseif $arrayCheckbox[chk_id].search_list==6} <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:22px; float; display:inline;" value="A" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">A</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:22px; float; display:inline;" value="B" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">B</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:22px; float; display:inline;" value="C" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">C</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:22px; float; display:inline;" value="D" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">D</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:22px; float; display:inline;" value="E" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">E</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:22px; float; display:inline;" value="F" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">F</span>
                  {elseif $arrayCheckbox[chk_id].search_list==5} <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:22px; float; display:inline;" value="A" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">A</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:22px; float; display:inline;" value="B" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">B</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:22px; float; display:inline;" value="C" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">C</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:22px; float; display:inline;" value="D" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">D</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:22px; float; display:inline;" value="E" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">E</span> {else} <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:22px; float; display:inline;" value="A" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">A</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:22px; float; display:inline;" value="B" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">B</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:22px; float; display:inline;" value="C" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">C</span> <span class="kt_a_1">
                <input type="checkbox" name="checkbox{$arrayCheckbox[chk_id].id}[]" style=" margin-left:2px; margin-top:22px; float; display:inline;" value="D" id="checkbox{$arrayCheckbox[chk_id].id}">
                </span><span class="kt_a_1" style="font-size: 68px;line-height: 68px;">D</span> {/if} </span> </li>
                 {if $arrayCheckbox[chk_id].right_error!="" }
                <li> <span style="width:660px; float:left; padding-left:13px; margin-top: 30px;  background-color:#ffffff;  color:#000000; margin-bottom:5px; display:inline; border:1px solid #19b10a; font-weight:bold;font-size: 68px;line-height: 68px;">正确答案：{$arrayCheckbox[chk_id].answer}<br>您的答案：{$arrayCheckbox[chk_id].sub}&nbsp;&nbsp;&nbsp;&nbsp;{$arrayCheckbox[chk_id].right_error}
                {if $arrayCheckbox[chk_id].resolve!=""}
                <br>问题解析：{$arrayCheckbox[chk_id].resolve}
                {/if}
                </span></li>
                {/if}
              {/section}
              {/if}
              
              {if $Fill==T}
              <li> <span style="width:660px; float:left; padding-left:13px;background-color:#ffffff;  color:#000000; margin-bottom:5px; display:inline; border:1px solid #19b10a; font-weight:bold;font-size: 48px;"> 随机问答： 填空题（每空{$fillFraction}分）</span></li>
              {section name=fil_id loop=$arrayFill}
              <li> <span class="kt" style="background-color:#FFFFFF; border:1px dashed #FF6600; color:#333333;"> <span style="padding-top:4px; float:left;font-size: 68px;line-height: 68px;">
               
            {util->mreplace p=$arrayFill[fil_id].content p2=$arrayFill[fil_id].id }
             
              </span> </span></li>
                 {if $arrayFill[fil_id].right_error!="" }
                 <li> <span style="width:660px; float:left; padding-left:13px; background-color:#ffffff;  color:#000000; margin-bottom:5px; display:inline; border:1px solid #19b10a; font-weight:bold;font-size: 68px;margin-top: 30px;">正确答案：{$arrayFill[fil_id].answer}<br>您的答案：{$arrayFill[fil_id].sub}&nbsp;&nbsp;&nbsp;&nbsp;{$arrayFill[fil_id].right_error}
                   {if $arrayFill[fil_id].resolve!=""}
                <br>问题解析：{$arrayFill[fil_id].resolve}
                {/if}
                 </span></li>
                 {/if}
              {/section}
              {/if}
              
              {if $Judgment==T}
              <li> <span style="width:660px; float:left; padding-left:13px; background-color:#ffffff;  color:#000000; margin-bottom:5px; display:inline; border:1px solid #19b10a; font-weight:bold;font-size: 48px;"> 随机问答： 判断题 每题{$judgmentFraction}分</span> </li>
              {section name=jud_id loop=$arrayJudgment}
              <li> <span class="kt"> <span class="kt_t" style="font-size: 68px;line-height: 68px;">
                {$arrayJudgment[jud_id].content}</span> </span> 
                <!--  <span class="kt_a">
            
                        <span class="kt_a_2">A.接口是一种用来定义程序的协议</span>                    </span>--> 
                <span class="kt_a" style="margin-top: 30px;"> <span class="kt_a_1">
                <input type="radio" name="judgment{$arrayJudgment[jud_id].id}" style="margin-top:2px; margin-left:2px; float:left; display:inline;" value="正确" id="judgment{$arrayJudgment[jud_id].id}">
                </span><span class="kt_a_1" style="width:185px;font-size: 68px;line-height: 68px;">正确</span><span class="kt_a_1">
                <input type="radio" name="judgment{$arrayJudgment[jud_id].id}" style="margin-top:2px; margin-left:2px; float:left; display:inline;" value="错误" id="judgment{$arrayJudgment[jud_id].id}">
                </span><span class="kt_a_1" style="width:185px;font-size: 68px;line-height: 68px;">错误</span></span></li>
                    {if $arrayJudgment[jud_id].right_error!="" }
                 <li> <span style="width:660px; float:left; padding-left:13px;  background-color:#ffffff;  color:#000000; margin-bottom:5px;margin-top: 32px; display:inline; border:1px solid #19b10a; font-weight:bold;font-size: 48px;">正确答案：{$arrayJudgment[jud_id].answer}<br>您的答案：{$arrayJudgment[jud_id].sub}&nbsp;&nbsp;&nbsp;&nbsp;{$arrayJudgment[jud_id].right_error}
                   {if $arrayJudgment[jud_id].resolve!=""}
                <br>问题解析：{$arrayJudgment[jud_id].resolve}
                {/if}
                 </span></li>
                 {/if}
              {/section}
              {/if}
              </p>
              <p> </p>
              <p>{if $Answer==T}
              <li> <span style="width:660px; float:left; padding-left:13px; line-height:28px;  background-color:#ffffff;  color:#000000; margin-bottom:5px; display:inline; border:1px solid #19b10a; font-weight:bold;"> 随机问答： 简答题（每题{$answerFraction}分，共{$Answers}题）</span></li>
              {section name=ans_id loop=$arrayAnswer}
              <li> <span class="kt"> <span class="kt_t">
                {$arrayAnswer[ans_id].content} </span> </span> <span style="float:left; padding-left:25px;">
                <textarea name="answer{$arrayAnswer[ans_id].id}" id="answer{$arrayAnswer[ans_id].id}" style="width:630px; padding-left:5px; float:left; line-height:25px; border:1px solid #AAAAAA; height:200px;" cols="" rows=""></textarea>
                </span> </li>
                {if $arrayAnswer[ans_id].right_error!="" }
                <li> <span style="width:660px; float:left; padding-left:13px; padding-right:10px; line-height:28px;  background-color:#ffffff;  color:#000000; margin-bottom:5px; display:inline; border:1px solid #19b10a; ">正确答案：{$arrayAnswer[ans_id].answer}
                </span></li>
                
                <li> <span style="width:660px; float:left; padding-left:13px; padding-right:10px; line-height:28px;  background-color:#ffffff;  color:#000000; margin-bottom:5px; display:inline; border:1px solid #19b10a; ">您的答案：{$arrayAnswer[ans_id].sub}&nbsp;&nbsp;&nbsp;&nbsp;{$arrayAnswer[ans_id].right_error}
                  {if $arrayAnswer[ans_id].resolve!=""}
                <br>问题解析：{$arrayAnswer[ans_id].resolve}
                {/if}
                </span></li>
                
                
                
                {/if}
              {/section}
              {/if}
              
              {if $Discourse==T}
              <li> <span style="width:660px; float:left; padding-left:13px; line-height:28px; background-color:#ffffff;  color:#000000; margin-bottom:5px; display:inline; border:1px solid #19b10a; font-weight:bold;"> 随机问答： 论述题（每题{$discourseFraction}分，共{$Discourses}题）</span></li>
              {section name=dis_id loop=$arrayDiscourse}
              <li> <span class="kt"> <span class="kt_t">
                {$arrayDiscourse[dis_id].content}</span> </span> <span style="float:left; padding-left:25px;">
                <textarea name="discourse{$arrayDiscourse[dis_id].id}" style="width:630px; padding-left:5px; float:left; line-height:25px; border:1px solid #AAAAAA; height:300px;" id="discourse{$arrayDiscourse[dis_id].id}" rows="15"></textarea>
                </span></li>
                     {if $arrayDiscourse[dis_id].right_error!="" }
                    <li> <span style="width:660px; float:left; padding-left:13px; padding-right:10px; line-height:28px;  background-color:#ffffff;  color:#000000; margin-bottom:5px; display:inline; border:1px solid #19b10a; ">正确答案：{$arrayDiscourse[dis_id].answer}</span></li>
                    <li> <span style="width:660px; float:left; padding-left:13px; padding-right:10px; line-height:28px;  background-color:#ffffff;  color:#000000; margin-bottom:5px; display:inline; border:1px solid #19b10a; ">您的答案：{$arrayDiscourse[dis_id].sub}&nbsp;&nbsp;&nbsp;&nbsp;{$arrayDiscourse[dis_id].right_error}
                      {if $arrayDiscourse[dis_id].resolve!=""}
                <br>问题解析：{$arrayDiscourse[dis_id].resolve}
                {/if}
                    </span></li>

                    {/if}
              {/section}
              {/if}
            </ul>
          </div>
          <div class="k_x"><a name="judgment"></a>
            <input type="hidden" name="type_id" id="type_id" value="{$type_id}" />
            <input type="hidden" name="exam_id" id="exam_id" value="{$exam_id}" />
            <input type="hidden" name="arrayValue" id="arrayValue" value="{$arrayValue}" />
          </div>
        </div>
        <div style="text-align: center;margin-bottom: 20px;"> <a href="Random_Answer.php?type_id={$type_id}&exam_id={$exam_id}"><img src="images/xyt.jpg" /> </a></div>
      </div>
    	</form>
    </div>
    </div>
<!--内容结束 -->