<script src="Scripts/Random_Answer.js" type="text/javascript"></script>
<script src="{util->baseUrl}/Scripts/jquery-1.4.2.js"></script>
<script language="javascript">
        function showDhList(x){ldelim}
            $("#"+x).slideToggle('fast');
        {rdelim}

    </script>
<!--内容开始 -->
<div id="sub">
	<div id="sub_left">
    	<div class="left_fl">
        	<div class="left_fl_bt"><img src="images/38.jpg" alt="" /></div>
            	<div id="PARENT">
                	<ul id="left_fl_con1">
{foreach from=$types item=type_id}
 						<li><a href="#"  onClick="showDhList('a_{$type_id}')">{section name=types_id loop=$typeNames}{if $typeNames[types_id].id==$type_id}{$typeNames[types_id].typename}{/if}{/section}</a>
                        	<ul id="a_{$type_id}" class="collapsed">
       					{section name=exam_id loop=$examTypes}
                        	{if $type_id==$examTypes[exam_id].pro_class}
       							<li><a href="search_Training.php?know_id={$examTypes[exam_id].id}&searches={$smarty.session.searches}" title="{$examTypes[exam_id].title}">{util->msubstr p=$examTypes[exam_id].title p1=0 p2=18 p3="..."}</a></li>
                            {/if}
       					{/section}
      						</ul>
    					</li>
{/foreach}

					</ul>
				</div>
            </div>
        </div>
        <div id="sub_right">
        {if $array!="F"}
        	<div class="right">
            	<div class="right_bt">{$smarty.get.type_id}</div>
                <div class="right_con">
                    <div class="right_con_bt">{util->msubstr p=$arrayExams[0].title p1=0 p2=48 p3="..."}</div>
                    <div class="right_con_texts">
                        <iframe name="content" src="CoalMine_Backstage/upfiles/Trainingmaterials/{$arrayExams[0].attachment}"  frameborder="0" width="100%" height="100%" ></iframe>
                    </div>
                </div>
            </div>
        {else}
        	<div class="right">
            <img src="images/none2.jpg" alt="" />
            </div>
        {/if}
        </div>
    </div>