<LINK rel=stylesheet type=text/css href="{util->baseUrl}/css/login.css">
<script language="javascript">
function chklogin(form){ldelim}  
        if(form.pro_class.value==''){ldelim}
            alert('请选择类别！');
            form.pro_class.focus();
            return false; 
        {rdelim}
          if(form.pro_type.value==''){ldelim}
            alert('请选择题型！');
            form.pro_type.focus();
            return false;
        {rdelim}
	    return true;
    {rdelim}
</script>
<div id="box">
  <div id="top3"></div>
    <div id="con">
    	<div class="con_c">
          <form id="form1" name="form1" method="post" target="_blank" onsubmit="return chklogin(this)">
           	     
       	  <div class="con_c_l">
            	<ul>
                    {if $smarty.session.name == ''}
                    <li><span class="font1">用户名称：</span>
                        <input name="netname" class="font2" type="text"/></li>
                    <li><span class="font1">密&nbsp;&nbsp;&nbsp;&nbsp;码：</span><input name="password" class="font2" type="password" /></li>
                    {/if}
                    <li><span class="font1">选择类别：</span>
						<select name="pro_class" id="pro_class" class="font2">
                        	<option value="" selected="selected">请选择类别</option>
                            {$displayType}
                      	</select>
                    </li>
                    <li><span class="font1">选择题型：</span>
                      	<select name="pro_type" id="pro_type" class="font2">
                        	<option value="" selected="selected">请选择题型</option>
                         	{html_options options=$arrayTypes}
                      	</select>
                    </li>
                    <li style="padding-left:140px;"><a href="updatepassword.php">修改密码</a> </li>
                </ul>
          </div>
            <div class="con_c_r">
            	<div class="con_c_r_a">
            	  <input type="image" name="submit" id="submit" src="images/34.jpg" />
           	  </div>
            </div>
               </form>
        </div>
       
    </div>
</div>
