<script src="Scripts/Random_Answer.js" type="text/javascript"></script>
<!--内容开始 -->
<div id="sub">
	<div id="sub_left">
    	<div class="left_fl">
        	<div class="left_fl_bt"><img src="images/38.jpg" alt="" /></div>
            	<div id="PARENT">
                	<ul id="left_fl_con1">
{php}$i=0;{/php}

{section name=type_id loop=$examType}

{php} $i++; {/php}

 						<li><a href="#" onClick="DoMenu('ChildMenu{php} echo $i; {/php}')">{util->getTypename p=$examType[type_id].pro_class p1=0 p2=15 p3="..."}</a>
                        	<ul id="ChildMenu{php} echo $i; {/php}" class="collapsed">
       					{section name=exam_id loop=$examTypes}
                        	{if $examType[type_id].pro_class==$examTypes[exam_id].pro_class}
       							<li><a href="Training.php?know_id={$examTypes[exam_id].id}" title="{$examTypes[exam_id].title}">{util->msubstr p=$examTypes[exam_id].title p1=0 p2=18 p3="..."}</a></li>
                            {/if}
       					{/section}
      						</ul>
    					</li>
{/section} 
					</ul>
				</div>
            </div>
        </div>
        <div id="sub_right">
        {if $array!="F"}
        	<div class="right">
            	<div class="right_bt">培训内容</div>
                <div class="right_con">
                	<div class="right_con_bt">{util->msubstr p=$arrayExams[0].title p1=0 p2=48 p3="..."}</div>
                    <div class="right_con_texts">
<iframe name="content" src="CoalMine_Backstage/upfiles/Trainingmaterials/{$arrayExams[0].attachment}"  frameborder="0" width="100%" height="100%" ></iframe>
                    </div>
                </div>
            </div>
        {else}
        	<div class="right">  <img src="images/none2.jpg" alt="" /></div>
        {/if}
        </div>
    </div>