<LINK rel=stylesheet type=text/css href="{util->baseUrl}/css/login.css">
<!--{if $update != "T"}-->
<!--<form name="form_updatepassword" method="post" action="" onSubmit="return chklogin(this)" >-->
<!--请输入您的准考证号：<input type="text" name="adminssion" value="" /><br>-->
<!--请输入密码：<input type="password" name="password" value="" />  <br>-->
<!--    <input type="submit" name="submit1" value="提交">-->
<!--</form>-->
<!--    -->
<!--{/if}-->
<!--    {if $update == "T"}-->
<!--<form name="form_updatepassword" method="post" action="" onSubmit="return chkupdate(this)">-->
<!--    请输入密码：<input type="text" name="password1" value="" /><br>-->
<!--    请输入重复输入密码：<input type="password" name="password2" value="" />  <br>-->
<!--    <input type="submit" name="submit2" value="提交">-->
<!--</form>-->
<!--    {/if}-->
<div id="box">
    <div id="con">
        <div class="con_c">
            {if $update!="T"}
            <form id="form1" name="form1" method="post" action="updatepassword.php" onsubmit="return chklogin(this)">

                <div class="con_c_l">
                    <ul>
                        <li><span class="font1">准考证号：</span><input name="admission" class="font2" type="text" value="" /></li>
                        <li><span class="font1">密&nbsp;&nbsp;&nbsp;&nbsp;码：</span><input name="password" class="font2" type="password" value=""/></li>
                        <li><input type="submit" name="submit1"  value="登录" /></li>
                    </ul>
                </div>
            </form>
            {/if}
            {if $update=="T"}
            <form id="form2" name="form2" method="post" action="updatepassword.php" onsubmit="return chkupdate(this)">

                <div class="con_c_l">
                    <ul>
                        <li><span class="font1">请输入密码：</span><input name="password1" class="font2" type="password" value="" /></li>
                        <li><span class="font1">请输入重复输入密码：</span><input name="password2" class="font2" type="password" value=""/></li>
                        <li>
                            <input type="hidden" name="admission"  value="{$admission}" />
                            <input type="submit" name="submit2"  value="提交" />
                        </li>
                    </ul>
                </div>

            </form>
            {/if}
        </div>
    </div>
</div>
<!--内容结束 -->
<script language="javascript">
    function chklogin(form){ldelim}
        if(form.admission.value==''){ldelim}
        alert('请输入准考证号！');
        form.admission.focus();
        return false;
        {rdelim}
        if(form.password.value==''){ldelim}
        alert('请输入密码！');
        form.password.focus();
        return false;
        {rdelim}
        return true;
    {rdelim}

    function chkupdate(form){ldelim}
        if(form.password1.value==''){ldelim}
        alert('请输入您要修改的密码！');
        form.password1.focus();
        return false;
        {rdelim}
        if(form.password1.value.length < 6){ldelim}
        alert('请输入6位以上密码！');
        form.password1.focus();
        return false;
        {rdelim}
        if(form.password2.value==''){ldelim}
        alert('请再输入一次！');
        form2.password2.focus();
        return false;
        {rdelim}
        if(form.password2.value != form.password1.value){ldelim}
        alert('请输入一致！');
        form.password2.focus();
        return false;
        {rdelim}
        return true;
    {rdelim}
</script>