<link href="{util->baseUrl}/css/style.css" rel="stylesheet" type="text/css" />
<link href="{util->baseUrl}/css/reset.css" rel="stylesheet" type="text/css" />
<script src="{util->baseUrl}/Scripts/common.js"></script>
<SCRIPT src="{util->baseUrl}/Scripts/jquery.js"></SCRIPT>
<SCRIPT src="{util->baseUrl}/Scripts/jquery.js"></SCRIPT>
<script>
    {literal}
    $(document).ready(function(){
        strArr = new Array();
        changeProClass();
    });
    function changeProClass(){
        strArr = [];
        var str = $('#form_addbccdinfo').serialize();
        $.post('getproquestions.php',str,function(data){
            var pagerString = '';
            var htmlContentString = ''
            var pageSize = 20;
            d = data.split('"***"');
            pagestr = d[0];
            aa = eval("("+pagestr+")");

            $('#displayquestions').html(d[1]);
            for(k in aa){
                pagerString = "";
                var countPage = Math.ceil(aa[k] / pageSize);
                for(i = 1;i <= countPage && 10 >= i;i++){
                    if(1 == i){
                        pagerString +='<a>'+i+'</a> '
                    } else {
                        pagerString += '&nbsp;<a href="javascript:void(0)" onclick="paging('
                            +i+','+'\''+k+'\''+')">'+i+'</a>&nbsp;'
                    }
                }
                $("#pager"+k).html(pagerString);
            }
        });
    }
    function paging(page,k){
        getCheckboxValue();
        var str = $('#form_addbccdinfo').serialize()+"&offset="+page+"&type="+k;
        $.post('getproquestions.php',str,function(data){
            var pagerString = '';
            var htmlContentString = ''
            var pageSize = 20;
            d = data.split("\"***\"");
            pagestr = d[0];
            aa = eval("("+pagestr+")");

            $('#displayquestions').html(d[1]);
            for(m in aa){
                pagerString = "";
                var countPage = Math.ceil(aa[m] / pageSize);
                if(m == k){
                    for(i = page - 5;i <= page + 5 && i <= countPage;i++){
                        if(0 < i){
                            if(i == page){
                                pagerString += '<a>'+i+'</a>'
                            } else {
                                pagerString += '&nbsp;<a href="javascript:void(0)" onclick="paging('
                                    +i+','+'\''+m+'\''+')">'+i+'</a>&nbsp;'
                            }
                        }
                    }
                    $("#pager"+m).html(pagerString);
                }else{
                    pagerString = "";
                    var countPage = Math.ceil(aa[m] / pageSize);
                    for(i = 1;i <= countPage && 10 >= i;i++){
                        if(1 == i){
                            pagerString +='<a>'+i+'</a> '
                        } else {
                            pagerString += '&nbsp;<a href="javascript:void(0)" onclick="paging('
                                +i+','+'\''+m+'\''+')">'+i+'</a>&nbsp;'
                        }
                    }
                    $("#pager"+m).html(pagerString);
                }
            }
            $("#checkedquestions").attr("value",strArr.join('@'));
        });
    }
    function checkall(flag){
        return chkinputbccdinfo() && chknumber(flag);
    }
    function chkinputbccdinfo(){
        if($('#pro_class').val() == 0){
            alert('请选择所属类别！');
            $('#pro_class').focus();
            return false;
        }
        if($('#title').val() == ''){
            alert('请输入标题！');
            $('#title').focus();
            return false;
        }

        if($('#template').val() == ''){
            alert('请选择考卷模板！');
            $('#template').focus();
            return false;
        }
        return true;
    }

    function chknumber(flag){
        var result = false;
        param = $('#form_addbccdinfo').serialize()+"&flag="+flag;
        $.ajax({
            type:'post',
            url:'chknumber.php',
            data:param,
            async:false,
            success:function(data){
                if(data != ''){
                    alert(data);
                }else{
                    result = true;
                }
            }
        })
        return result;
    }

    function getCheckboxValue(){
        $("input[type='checkbox'][name!='exam_user']:checked")
            .each(function(){
                if(!strArr.in_array($(this).val())){
                    strArr.push($(this).attr('name')+$(this).val());
                }
            })
    }

    Array.prototype.in_array = function(e){
        for(i=0;i<this.length;i++){
            if(this[i] == e){
                return true;
            }
        }
        return false;
    }
    {/literal}
</script>
<div id="con_right">
  <div class="right_con">
    <div class="right_con_bt">·{$smarty.get.big_type} < {$smarty.get.small_type}</div>
    <br />
    <br />
    <br />
    <DIV class="right_con_form">
      <form name="form_addbccdinfo" id="form_addbccdinfo" method="post" action="" enctype="multipart/form-data">
        <br />
        所属类别：
        <select name="pro_class" id="pro_class" class="input1" onchange="changeProClass()">
          <option value=0>请选择</option>
          
    	{$displayType}
    
        </select>
        <br />
        <br />
        试卷标题：
        <input type="text" id="title" name="title" size="65" class="input1" />
        <br/>
        <br/>
        考试人员：
        <br/> 
                <br/> 
<table width="98%" border="1" cellpadding="1" cellspacing="1" bordercolor="#FFFFFF" bgcolor="#CCCCCC">
        {section name=class_id loop=$arrayClass}
  <tr>
    <td style="padding-top:5px; padding-bottom:5px;" width="20%" align="center" bgcolor="#FFFFFF">{$arrayClass[class_id].typename}</td>
    <td style="padding-top:5px; padding-bottom:5px; padding-left:6px;" width="80%" bgcolor="#FFFFFF">
    {section name=user_id loop=$tb_user}
        {if $tb_user[user_id].typework==$arrayClass[class_id].id}
        	<input name="exam_user[]" type="checkbox" id="exam_user" value="{$tb_user[user_id].id}" />{$tb_user[user_id].name}
        {/if}
    {/section} 
	</td>
  </tr>
        {/section} 
</table>
        <br/>
        <br/>
        开始时间：
        <select name="years" id="years">
          
       
                    {html_options options=$arrayYear selected=$years}
                
        
        </select>
        年
        <select name="months" id="months">
          
          
                    {html_options options=$arrayMonth selected=$months}
                
        
        </select>
        月
        <select name="days" id="days">
          
          
                    {html_options options=$arrayDay selected=$days}
                
        
        </select>
        日
        <select name="hours" id="hours">
          
          
                    {html_options options=$arrayHour selected=9}
                
        
        </select>
        时
        <select name="minutes" id="minutes">
          
          
                    {html_options options=$arrayMinute }
                
        
        </select>
        分
        <select name="seconds" id="seconds">
          
          
                    {html_options options=$arraySecond }
                
        
        </select>
        秒 <br />
        <br/>
        结束时间：
        <select name="year" id="year">
          
          
                    {html_options options=$arrayYear selected=$years}
                
        
        </select>
        年
        <select name="month" id="month">
          
          
                    {html_options options=$arrayMonth selected=$months}
                
        
        </select>
        月
        <select name="day" id="day">
          
          
                    {html_options options=$arrayDay selected=$days }
                
        
        </select>
        日
        <select name="hour" id="hour">
          
          
                    {html_options options=$arrayHour selected=10}
                
        
        </select>
        时
        <select name="minute" id="minute">
          
          
                    {html_options options=$arrayMinute selected=30}
                
        
        </select>
        分
        <select name="second" id="second">
          
          
                    {html_options options=$arraySecond selected=0 }
                
        
        </select>
        秒
        <br/>
        <br/>
<!--        单选题：-->
<!--        <input name="rad" type="text" id="rad" size="5" value="30" class="input1"  />-->
<!--        多选题：-->
<!--        <input name="che" type="text" id="che" size="5" value="20" class="input1"  />-->
<!--        填空题：-->
<!--        <input name="fil" type="text" id="fil" size="5" value="10" class="input1"  />-->
<!--        判断题：-->
<!--        <input name="jud" type="text" id="jud" size="5" value="10" class="input1"  />-->
<!--        简答题：-->
<!--        <input name="ans" type="text" id="ans" size="5" value="8" class="input1"  />-->
<!--        论述题：-->
<!--        <input name="dis" type="text" id="dis" size="5" value="2" class="input1" />-->
         <br />
         <br />
        请选择考试模板：<select id="template" name="template">
            <option value="">请选择</option>
            {html_options options = $tb_template}
        </select>
        <input type="hidden" id="checkedquestions" name="checkedquestions" value="" />
        <br/>
        <br/>
           <input type="submit" name="submit2" id="submit2" value="随机生成试卷" onclick="return checkall(0)"/>
        <br />
        <br/>
        <DIV id=main>
          <DIV id=mid8>
            <DIV class=wen-ind8 id="displayquestions">
              <!--section 二叉树的定义-->
              {section name=id loop=$tb_exam_type}
              <DIV class=section title={$tb_exam_type[id].chinese}>
                <TABLE border=0 cellSpacing=0 cellPadding=0 width="697" style="margin-top:8px; display:inline; background-color:#f6f5f5; border:1px solid #c6c4c4;">
                  <TBODY>
                    <TR>
                      <TD class=bt-tdleft><H5>{$tb_exam_type[id].chinese}</H5></TD>
                      <TD class=bt-tdm><DIV>
                          <DIV class=right2-bt><SPAN class=Text-t12>{$tb_exam_type[id].chinese}题题库。</SPAN><BR>
                            <DIV><IMG src="images/row.jpg" width=4
      height=10>&nbsp;提示：在展开后的列表中存储了所有{$tb_exam_type[id].chinese}的内容，管理员可以根据需要进行选择......</DIV>
                          </DIV>
                        </DIV></TD>
                      <TD class=bt-tdr><SPAN class=control><A onfocus=this.blur()
      onclick="openShutManager(this,'{$tb_exam_type[id].id}',false,'折叠','展开');">展开</A></SPAN></TD>
                    </TR>
                  </TBODY>
                </TABLE>
                <DIV style="DISPLAY: none" id={$tb_exam_type[id].id}>
                 &nbsp;&nbsp;
                  <DIV class=nr-2>
                    <PRE class=brush:java>
<div style="width: 95%; border: 1px solid #21de26; ">

    {section name=ids loop=$tb_exam}
    {if $tb_exam[ids].pro_type==$tb_exam_type[id].english}
    <div style="width:100%; border-top: 1px solid #21de26; ">
        <ul>
            <li style="width:10%; line-height:23px; float:left; text-align:center; border-right: 1px solid #21de26;">

    	  <input type="checkbox" name="{$tb_exam[ids].pro_type}[]" id="{$tb_exam[ids].pro_type}[]" value="{$tb_exam[ids].id}">
            </li>
              <li style="width:90%; float:left; padding-left:6px; ">
                  {if $tb_exam[ids].pro_type == 'fill'}
                  {$tb_exam[ids].content|replace:"()":"(     )"}
                  {else}
    	            {$tb_exam[ids].content}
                  {/if}
            </li>
         </ul>
    </div>
    {/if}
    {/section}
</div>

</PRE>
                  </DIV>
                </DIV>
              </DIV>
              <!--section 二叉树的性质-->
              {/section} </DIV>
          </DIV>
        </DIV>
        <br />
        权限：绝密
        <input type="radio" name="whether" id="whether" value="1"   checked="checked" />
        公开
        <input name="whether" type="radio" id="whether" value="0"/>
        <br />
        <br />   
          <input type="submit" name="submit" id="submit" value="手动生成试卷" onclick="return checkall(1)"/>
        <br />
        <br />
      </form>
    </DIV>
    <BR>
  </div>
</div>
