<link href="{util->baseUrl}/css/style.css" rel="stylesheet" type="text/css" />
<link href="{util->baseUrl}/css/reset.css" rel="stylesheet" type="text/css" />
<div id="con_right">
    <div class="right_con">
        <div class="right_con_bt">·{$smarty.get.big_type} < {$smarty.get.small_type}</div>
        <br />
        <br />
        <br />
        <DIV class="right_con_form">
            <form name="form_addbigtype" method="post" action="" onsubmit="return chkInputBigtype(this)">
                <div style="width:100%; text-align:left; padding-top:5px; padding-left:50px">
                    所属分类（不填写为一级分类）：<select name="pro_class" id="pro_class" class="input1" >
                    <option value=0>请选择</option>
                    {$displayType}
                </select>
                    <br />
                    分类名称：<input type="text" name="typename" size="30" class="input"/><br /><br />
                    <input type="submit" value="添加" />&nbsp;&nbsp;<input type="reset" value="重置" />
                </div>
            </form>
        </DIV>
        <BR>
    </div>
</div>

<script language="javascript">
    function chkInputBigtype (form) {ldelim}
    if (form.typename.value == "") {ldelim}
    alert("请输入类别名称！");
    form.typename.focus();
    return false;
    {rdelim}
    return true;
    {rdelim}
</script>