<link href="{util->baseUrl}/css/style.css" rel="stylesheet" type="text/css" />
<link href="{util->baseUrl}/css/reset.css" rel="stylesheet" type="text/css" />
<div id="con_right">
    <div class="right_con">
        <div class="right_con_bt">·{$smarty.get.big_type} < {$smarty.get.small_type}</div>
        <br />
        <br />
        <br />
        <DIV class="right_con_form">
            <form name="form_emttr" method="post" action="" onsubmit="return chkEmttr(this)">
                <div style="width:100%; text-align:left; padding-top:5px; padding-left:50px">
                    总分：<input type="text" name="totalscore" size="30" class="input"/><br /><br />
                    <br />
                    分数线：<input type="text" name="passscore" size="30" class="input"/><br /><br />
                    <input type="submit" name="addemattr" value="添加" />&nbsp;&nbsp;<input type="reset" value="重置" />
                </div>
            </form>
        </DIV>
        <BR>
        <DIV style="padding-left:56px; padding-top:56px;text-align: center">
            <DIV style="padding-left:6px; text-align: center">
                <UL>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 20%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER:#21de26 1px solid;">序号</LI>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 20%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER:#21de26 1px solid;">总分</LI>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 20%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER:#21de26 1px solid;">分数线</LI>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 20%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER:#21de26 1px solid;">操作</LI>
                </UL>
            </DIV>
            {php} $i = 1;{/php}
            {section name=tID loop=$emattrArr}
            <DIV style="padding-left:6px; text-align: center">
                <UL>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 20%; FLOAT: left; text-align:center; HEIGHT: 23px; BORDER:#21de26 1px solid;">{php}echo $i;{/php}</LI>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 20%; FLOAT: left; text-align:center; HEIGHT: 23px; BORDER:#21de26 1px solid;">{$emattrArr[tID].totalscore}</LI>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 20%; FLOAT: left; text-align:center; HEIGHT: 23px; BORDER:#21de26 1px solid;">{$emattrArr[tID].passscore}</LI>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 20%; FLOAT: left; text-align:center; HEIGHT: 23px; BORDER:#21de26 1px solid;">
                        <a href="{util->baseUrl}/addemattr.php?f=edit&id={$emattrArr[tID].id}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}">更改</a>&nbsp;<a href="javascript:if(window.confirm('确定删除？')==true){ldelim}window.location.href='{util->baseUrl}/addemattr.php?f=del&id={$emattrArr[tID].id}&big_type={$smarty.get.big_type}&small_type={$smarty.get.small_type}';{rdelim}">删除</a>
                    </LI>
                </UL>
            </DIV>
            {php} $i++;{/php}
            {/section}
        </DIV>
        {if $isShow == "T"}
        <div class="right_con_form">
            <form name="form_editemattr" method="post" action="{util->baseUrl}/addemattr.php?big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}" >
                <div style="width:100%; text-align:left; padding-top:5px; padding-left:50px">
                    总分：<input type="text" id="totalscore" name="totalscore" size="30" class="input" value="{$bigtype[0].totalscore}"/><br /><br />
                    <br />
                    <br />
                    分数线：<input type="text" id="passscore" name="passscore" size="30" class="input" value="{$bigtype[0].passscore}"/><br /><br />
                    <input type="hidden" name="f" value="edit" />
                    <input type="hidden" name="id" value="{$bigtype[0].id}" />
                    <input type="submit" name="editemattr" value="更改" />
                </div>
            </form>
        </div>
        {/if}
    </div>
</div>

<script language="javascript">
{literal}
    function chkEmttr (form) {
    if (form.totalscore.value == "") {
        alert("请输入总分！");
        form.totalscore.focus();
        return false;
    }
    if (isNaN(form.totalscore.value)) {
        alert("请输入数字！");
        form.totalscore.focus();
        return false;
    }
    if (form.passscore.value == "") {
        alert("请输入分数线！");
        form.totalscore.focus();
        return false;
    }
    if (isNaN(form.passscore.value)) {
        alert("请输入数字！");
        form.totalscore.focus();
        return false;
    }
    if (new Number(form.passscore.value) >= new Number(form.totalscore.value)) {
        alert("分数线不能大于等于总分，请重新填写！");
        form.totalscore.focus();
        return false;
    }
    return true;
    }

{/literal}
</script>