<link href="{util->baseUrl}/css/style.css" rel="stylesheet" type="text/css" />
<link href="{util->baseUrl}/css/reset.css" rel="stylesheet" type="text/css" />
<div id="con_right">
    <div class="right_con">
        <div class="right_con_bt">·{$smarty.get.big_type} < {$smarty.get.small_type}</div>
        <br />
        <br />
        <br />
        <DIV class="right_con_form">
            <form name="form_addexamtypes" method="post" action="" onsubmit="return chkInputBigtype(this)">
                <div style="width:100%; text-align:left; padding-top:5px; padding-left:50px">
                    所属分类（不填写为一级分类）：<select name="pro_type" id="pro_type" class="input1" >
                    <option value=0>请选择</option>
                    {$tb_exam_type}
                </select>
                    <br />
                    <br />
                    分类名称：<input type="text" name="chinese" size="30" class="input"/><br/><br/>
                    英文名称：<input type="text" name="english" size="30" class="input"/><br/><br/>
                    <input type="submit" value="添加" />&nbsp;&nbsp;<input type="reset" value="重置" />
                </div>
            </form>
        </DIV>
        <BR>
    </div>
</div>

<script language="javascript">
    function chkInputBigtype (form) {ldelim}
    if (form.chinese.value == "") {ldelim}
    alert("请输入类别名称！");
    form.chinese.focus();
    return false;
    {rdelim}
    if (form.english.value == "") {ldelim}
    alert("请输入英文名称！");
    form.english.focus();
    return false;
    {rdelim}
    return true;
    {rdelim}
</script> 