<link href="{util->baseUrl}/css/style.css" rel="stylesheet" type="text/css" />
<link href="{util->baseUrl}/css/reset.css" rel="stylesheet" type="text/css" />
<!--右侧-->
<div id="con_right">
  <div class="right_con">
    <div class="right_con_bt">·{$smarty.get.big_type} < {$smarty.get.small_type}</div>
    <br />
    <br />
    <br />
    <DIV>
      <DIV style="padding-left:6px;">
        <UL>
          <LI style="LINE-HEIGHT: 25px; WIDTH: 43%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">姓名（工种）</LI>
          <LI style="LINE-HEIGHT: 25px; WIDTH: 20%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">权限 </LI>
          
          <LI style="LINE-HEIGHT: 25px; WIDTH: 20%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">状态 </LI>
          <LI style="LINE-HEIGHT: 25px; WIDTH: 15%; FLOAT: left; text-align:center; HEIGHT: 25px; border-bottom:#21de26 1px solid;">操作 </LI>
        </UL>
      </DIV>
      {section name=id loop=$bcjyzs.data}
      <DIV style="padding-left:6px;">
        <UL>
          <LI style="LINE-HEIGHT: 23px; WIDTH: 43%; padding-left:10px; FLOAT: left; HEIGHT: 23px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;"> {$bcjyzs.data[id].name}（
             {section name=bccdnameids loop=$arrayBccdnames1}
    	{if $arrayBccdnames1[bccdnameids].id==$bcjyzs.data[id].typework}
       {$arrayBccdnames1[bccdnameids].typename}
        {/if}
        {/section}）
 </LI>
          <LI style="LINE-HEIGHT: 23px; WIDTH: 20%; FLOAT: left; text-align:center; HEIGHT: 23px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">{if $bcjyzs.data[id].freeze==1}冻结{else}正常{/if} </LI>
          <LI style="LINE-HEIGHT: 23px; WIDTH: 20%; FLOAT: left; text-align:center; HEIGHT: 23px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">{if $bcjyzs.data[id].permissions==1}队长{elseif $bcjyzs.data[id].permissions==2}管理员{elseif $bcjyzs.data[id].permissions==3}超级管理员{else}员工{/if} </LI>
          <LI style="LINE-HEIGHT: 23px; WIDTH: 15%; FLOAT: left; text-align:center; HEIGHT: 23px; border-bottom:#21de26 1px solid;"> <a href="?edit=t&id={$bcjyzs.data[id].id}&imagename={$bcjyzs.data[id].picture}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}" class="a1">更改</a></LI>
        </UL>
      </DIV>
      {/section} 
   </DIV>
     <br />
    <br />
    <br />
    <div style="padding-left:6px; padding-top:6px;"> {if $bcjyzs.data!=false}
      <div style="height:22px;  float:left">
        <div style="width:400px; height:22px; border:1px solid #AED4EB; padding-left:5px; float:left; padding-top:3px"> <strong> 共{$bcjyzs.countRs}篇&nbsp;&nbsp;每页{$bcjyzs.pageSize}篇&nbsp;&nbsp;第{$bcjyzs.page}页/共{$bcjyzs.countPage}页&nbsp;&nbsp;<a href="{util->baseUrl}/aeditadmin.php?page={$bcjyzs.first}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}" class="a1">首页</a>&nbsp;&nbsp;<a href="{util->baseUrl}/aeditadmin.php?page={$bcjyzs.previous}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}" class="a1">上页</a>&nbsp;&nbsp;<a href="{util->baseUrl}/aeditadmin.php?page={$bcjyzs.next}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}" class="a1">下页</a>&nbsp;&nbsp;<a href="{util->baseUrl}/aeditadmin.php?page={$bcjyzs.last}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}" class="a1">尾页</a></strong> </div>
        {section name=numId loop=$bcjyzs.arrayNum}
        <div style="width:3px; height:22px; float:left"></div>
        <div style="width:23px; height:22px; padding-left:5px; float:left; border:1px solid #AED4EB; padding-top:3px ;{if $bcjyzs.arrayNum[numId]==$bcjyzs.page} background-color:#51D26B {/if} "> <a href="{util->baseUrl}/aeditadmin.php?page={$bcjyzs.arrayNum[numId]}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}" class="{if $bcjyzs.arrayNum[numId]==$bcjyzs.page}a2{else}a6{/if}">{$bcjyzs.arrayNum[numId]}{if $bcjyzs.arrayNum[numId]==$bcjyzs.page}{/if}</a> </div>
        {/section} 
        </div>
      {/if} </div>
    <br/>
    {if $edit=='t'}
    <div class="right_con_form">
     <form name="form_addserver" method="post" enctype="multipart/form-data" style="margin:0px; padding:0px;">         
                <p>员工名称：
                <input type="text" name="servername" id="servername" value="{$bcjyz[0].name}" size="60" class="input1" /><br/><br/>
                             
                                                                    权限：
                                                                    <input name="permissions" type="radio" id="permissions" value="1" {if $bcjyz[0].permissions==1} checked="checked"{/if}  />
                                                                    队长 <input name="permissions" type="radio" id="permissions" value="2" {if $bcjyz[0].permissions==2} checked="checked"{/if}  />
                                                                    管理员
                                                                     <input name="permissions" type="radio" id="permissions" value="3" {if $bcjyz[0].permissions==3} checked="checked"{/if}  />
                                                                    超级管理员<br/><br/>    
                                                                    冻结/解冻：
    <input type="radio" name="freeze" id="freeze" value="1" {if $bcjyz[0].freeze==1} checked="checked"{/if} />
    冻结
    <input type="radio" name="freeze" id="freeze" value="0" {if $bcjyz[0].freeze==0} checked="checked"{/if} />
    解冻
                  <br/><br/>                                                      

    <input type="hidden" name="bcjyzid" value="{$bcjyz[0].id}">
         <input type="submit" name="submit" id="submit" value="提交" />&nbsp;&nbsp;<input type="reset" value="重写" />
                </p>
  </form> 
    </div>
    {/if} </div>
</div>