<link href="{util->baseUrl}/css/style.css" rel="stylesheet" type="text/css" />
<link href="{util->baseUrl}/css/reset.css" rel="stylesheet" type="text/css" />
<script language="javascript" src="{util->baseUrl}/Scripts/checkbox.js"></script>
<!--右侧-->
<div id="con_right">
  <div class="right_con">
    <div class="right_con_bt">·{$smarty.get.big_type} < {$smarty.get.small_type}</div>
    <br />
    <br />
    <br />
    <DIV>
      <DIV style="padding-left:6px;">
        <UL>
          <LI style="LINE-HEIGHT: 25px; WIDTH: 8%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">全选</LI>
          <LI style="LINE-HEIGHT: 25px; WIDTH: 15%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">一级标题 </LI>
          <LI style="LINE-HEIGHT: 25px; WIDTH: 37%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">二级标题 </LI>
          <LI style="LINE-HEIGHT: 25px; WIDTH: 15%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">添加时间 </LI>
          <LI style="LINE-HEIGHT: 25px; WIDTH: 19%; FLOAT: left; text-align:center; HEIGHT: 25px; border-bottom:#21de26 1px solid;">操作 </LI>
        </UL>
      </DIV>
      <form method="post" name="form1" id="form1" action="">
      {section name=id loop=$bcjyzs.data}
      <DIV style="padding-left:6px;">
        <UL>
          <LI style="LINE-HEIGHT: 23px; WIDTH: 8%; padding-left:10px; FLOAT: left; HEIGHT: 23px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">  <input name="conn_id[]" type="checkbox" id="conn_id[]" value="{$bcjyzs.data[id].id}" />    
            <input type="hidden" name="images[]" id="images" value="{$bcjyzs.data[id].attachment}" />
          </LI>
          <LI style="LINE-HEIGHT: 23px; WIDTH: 15%; padding-left:10px; FLOAT: left; HEIGHT: 23px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;"> {util->msubstr p=$bcjyzs.data[id].titles p1=0 p2=12 p3="..."}</LI>
          
          <LI style="LINE-HEIGHT: 23px; WIDTH: 37%; padding-left:10px; FLOAT: left; HEIGHT: 23px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;"> {util->msubstr p=$bcjyzs.data[id].title p1=0 p2=60 p3="..."}</LI>
          <LI style="LINE-HEIGHT: 23px; WIDTH: 15%; FLOAT: left; text-align:center; HEIGHT: 23px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">{$bcjyzs.data[id].addtime} </LI>
          <LI style="LINE-HEIGHT: 23px; WIDTH: 19%; FLOAT: left; text-align:center; HEIGHT: 23px; border-bottom:#21de26 1px solid;"> <a href="upfiles/Trainingmaterials/{$bcjyzs.data[id].attachment}" target="_blank" class="a1">预览&nbsp;|&nbsp;<a href="?edit=t&id={$bcjyzs.data[id].id}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}" class="a1">更改&nbsp;|&nbsp;<a href="?delete=t&id={$bcjyzs.data[id].id}&imagename={$bcjyzs.data[id].attachment}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}" class="a1">删除</a></LI>
        </UL>
      </DIV>
      {/section}
      <br />
 <img src="images/bg_19-20.jpg" onclick="checkAll(form1,status)" width="62" height="25" />&nbsp;&nbsp;<img src="images/bg_14-14.jpg" onclick="switchAll(form1,status)"  width="62" height="25" />&nbsp;&nbsp; <img src="images/bg_07-08.jpg" width="62" height="25" onclick="uncheckAll(form1,status)" /> &nbsp;&nbsp;<input type="image" name="imageField" src="images/bg_14.jpg" />
      </form>
   </DIV>
    <br />
    <div style="padding-left:6px; padding-top:6px;"> {if $bcjyzs.data!=false}
      <div style="height:22px;  float:left">
        <div style="width:400px; height:22px; border:1px solid #AED4EB; padding-left:5px; float:left; padding-top:3px"> <strong> 共{$bcjyzs.countRs}篇&nbsp;&nbsp;每页{$bcjyzs.pageSize}篇&nbsp;&nbsp;第{$bcjyzs.page}页/共{$bcjyzs.countPage}页&nbsp;&nbsp;<a href="{util->baseUrl}/aeditbccdinfo.php?page={$bcjyzs.first}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}" class="a1">首页</a>&nbsp;&nbsp;<a href="{util->baseUrl}/aeditbccdinfo.php?page={$bcjyzs.previous}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}" class="a1">上页</a>&nbsp;&nbsp;<a href="{util->baseUrl}/aeditbccdinfo.php?page={$bcjyzs.next}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}" class="a1">下页</a>&nbsp;&nbsp;<a href="{util->baseUrl}/aeditbccdinfo.php?page={$bcjyzs.last}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}" class="a1">尾页</a></strong> </div>
        {section name=numId loop=$bcjyzs.arrayNum}
        <div style="width:3px; height:22px; float:left"></div>
        <div style="width:23px; height:22px; padding-left:5px; float:left; border:1px solid #AED4EB; padding-top:3px ;{if $bcjyzs.arrayNum[numId]==$bcjyzs.page} background-color:#51D26B {/if} "> <a href="{util->baseUrl}/aeditbccdinfo.php?page={$bcjyzs.arrayNum[numId]}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}" class="{if $bcjyzs.arrayNum[numId]==$bcjyzs.page}a2{else}a6{/if}">{$bcjyzs.arrayNum[numId]}{if $bcjyzs.arrayNum[numId]==$bcjyzs.page}{/if}</a> </div>
        {/section} 
        </div>
      {/if} </div>
    <br/>
    {if $edit=='t'}
    <div class="right_con_form">
      <form name="form_addbcjyz" method="post" action="" enctype="multipart/form-data" onsubmit="return chkInputfile(this)">
        <br />
       一级标题
        <input type="text" name="titles" size="65" value="{$bcjyz[0].titles}" class="input1" />
        <br />
        <br />
        二级标题：
        <input type="text" name="title" size="65" value="{$bcjyz[0].title}" class="input1" />
          <br />
          <br />
          所属类别：
          <select name="pro_class" id="pro_class" class="input1" >
              <option value="">请选择</option>

              {html_options options=$ktypes selected=$bcjyz[0].pro_class}

          </select>
          <br/>
          <br/>
        <br/>
        <br/>
        资料上传：
        <input name="zlfilename" type="file" class="input1" id="zlfilename" size="45" />
        <br/>
        <br/>
        <input type="hidden" name="bcjyzid" value="{$bcjyz[0].id}">
        <input type="submit" name="submit" value="提交">
        <br />
        <br />
      </form>
    </div>
    {/if} </div>
</div>
