<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>煤矿考试后台-管理中心</title>
</head>
<link href="{util->baseUrl}/css/style.css" rel="stylesheet" type="text/css" />
<link href="{util->baseUrl}/css/reset.css" rel="stylesheet" type="text/css" />
<body>
<div id="box"> 
  <!--头部开始 -->
  <div id="top" class="ac">
    <div class="top_right"><span class="font1"><a href="logout.php">退出系统</a></span> <span class="font2">{$smarty.session.back_name} （
    {if $smarty.session.permissions==0}
    员工
		{elseif $smarty.session.permissions==1}    
      队长  
        {elseif $smarty.session.permissions==2}    
        管理员
        {elseif $smarty.session.permissions==3}    
    超级管理员
    {/if}
    ） 欢迎登录，您上次登录的时间为：{$smarty.session.last_login_date}</span> </div>
  </div>
  <!--头部结束 --> 
  </div>
</body>
</html>
