<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>煤矿系统后台-管理中心</title>
</head>
<noscript><iframe src="*.html"></iframe></noscript>
<frameset rows="*" cols="*,1004,*" frameborder="no" framespacing="0" border="0">
	<frame src="{util->baseUrl}/blank.php" name="BLFrame" scrolling="no" noresize>
   	<frameset rows="99,*" frameborder="0">
		<frame src="{util->baseUrl}/aheader.php" name="headerwindow" scrolling="no">
		<frameset cols="253, *">
			<frame src="{util->baseUrl}/aleft.php" name="leftwindow" >
			<frame src="{util->baseUrl}/amain.php" name="mainwindow" >
		</frameset>
	</frameset>
	<frame src="{util->baseUrl}/blank.php" name="BRFrame" scrolling="no" noresize>
</frameset>
<noframes></noframes>