<link href="{util->baseUrl}/css/style.css" rel="stylesheet" type="text/css" />
<link href="{util->baseUrl}/css/reset.css" rel="stylesheet" type="text/css" />
<!--右侧-->
<div id="con_right">
  <div class="right_con">
    <div class="right_con_bt">·{$smarty.get.big_type} < {$smarty.get.small_type}</div>
    <br />
    <br />
    <br />
    <DIV>
      <DIV style="padding-left:6px;">
        <UL>
          <LI style="LINE-HEIGHT: 25px; WIDTH: 43%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">类别名称 </LI>
          <LI style="LINE-HEIGHT: 25px; WIDTH: 20%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">大类别名称 </LI>
          <LI style="LINE-HEIGHT: 25px; WIDTH: 20%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">添加时间 </LI>
          <LI style="LINE-HEIGHT: 25px; WIDTH: 15%; FLOAT: left; text-align:center; HEIGHT: 25px; border-bottom:#21de26 1px solid;">操作 </LI>
        </UL>
      </DIV>
     {section name=tID loop=$smalltypes}
		{if $smalltypes[tID].parentid!=0}
      <DIV style="padding-left:6px;">
        <UL>
          <LI style="LINE-HEIGHT: 23px; WIDTH: 43%; padding-left:10px; FLOAT: left; HEIGHT: 23px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">  {util->unHtml p=$smalltypes[tID].typename}</LI>
          <LI style="LINE-HEIGHT: 23px; WIDTH: 20%; padding-left:10px; FLOAT: left; HEIGHT: 23px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">  {section name=bID loop=$bigtypes}
			{if $smalltypes[tID].parentid==$bigtypes[bID].id}
			   {util->unHtml p=$bigtypes[bID].typename}
			{/if}
		{/section}</LI>          
          <LI style="LINE-HEIGHT: 23px; WIDTH: 20%; FLOAT: left; text-align:center; HEIGHT: 23px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">  {util->unHtml p=$smalltypes[tID].addtime} </LI>
          <LI style="LINE-HEIGHT: 23px; WIDTH: 15%; FLOAT: left; text-align:center; HEIGHT: 23px; border-bottom:#21de26 1px solid;">
           <a href="{util->baseUrl}/alistsmalltype.php?f=edit&id={$smalltypes[tID].id}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}">更改</a>&nbsp;<a href="javascript:if(window.confirm('确定删除？')==true){ldelim}window.location.href='{util->baseUrl}/alistsmalltype.php?f=del&id={$smalltypes[tID].id}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}';{rdelim}">删除</a> 
          </LI>
        </UL>
      </DIV>
      {/if}
      {/section} 
   </DIV>
    <br />
    <br />
    <br/>
     {if $isShow == "T"}
    <div class="right_con_form">
    
      <form name="form_editsmalltype" method="post" action="{util->baseUrl}/alistsmalltype.php">
    
                  小类名称：<input type="text" name="typename" size="30" class="input" value="{$smalltype[0].typename}"/><br /><br />
                  <input type="hidden" name="f" value="edit" /> 
                         所属大类：<select name="bigtypeid">
                     <option value="">-请选择-</option>
                     {html_options options = $arrayBtypeOption selected = $smalltype[0].parentid}
                  </select><br /><br />            
                  <input type="hidden" name="id" value="{$smalltype[0].id}" />
                   
                <input type="submit" value="更改" />&nbsp;&nbsp;<input type="reset" value="重置" />
   
            </form>  
        
    
      
    </div>
    {/if} </div>
</div>