<link href="{util->baseUrl}/css/style.css" rel="stylesheet" type="text/css" />
<link href="{util->baseUrl}/css/reset.css" rel="stylesheet" type="text/css" />
<!--右侧-->
<div id="con_right">
  <div class="right_con">
    <div class="right_con_bt">·{$smarty.get.big_type} < {$smarty.get.small_type}</div>
    <br />
    <br />
    <br />
    <DIV>
      <DIV style="padding-left:6px;">
        <UL>
          <LI style="LINE-HEIGHT: 25px; WIDTH: 63%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">类别名称 </LI>
          <LI style="LINE-HEIGHT: 25px; WIDTH: 20%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">添加时间 </LI>
          <LI style="LINE-HEIGHT: 25px; WIDTH: 15%; FLOAT: left; text-align:center; HEIGHT: 25px; border-bottom:#21de26 1px solid;">操作 </LI>
        </UL>
      </DIV>
     {section name=tID loop=$bigtypes}
      <DIV style="padding-left:6px;">
        <UL>
          <LI style="LINE-HEIGHT: 23px; WIDTH: 63%; padding-left:10px; FLOAT: left; HEIGHT: 23px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">{$bigtypes[tID].name}</LI>
          <LI style="LINE-HEIGHT: 23px; WIDTH: 20%; FLOAT: left; text-align:center; HEIGHT: 23px; BORDER-RIGHT: #21de26 1px solid; border-bottom:#21de26 1px solid;">{$bigtypes[tID].addtime}</LI>
          <LI style="LINE-HEIGHT: 23px; WIDTH: 15%; FLOAT: left; text-align:center; HEIGHT: 23px; border-bottom:#21de26 1px solid;"> 
           <a href="{util->baseUrl}/editknowledgetype.php?f=edit&id={$bigtypes[tID].id}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}">更改</a>&nbsp;<a href="javascript:if(window.confirm('确定删除？')==true){ldelim}window.location.href='{util->baseUrl}/editknowledgetype.php?f=del&id={$bigtypes[tID].id}&big_type={$smarty.get.big_type}&small_type={$smarty.get.small_type}';{rdelim}">删除</a>
          </LI>
        </UL>
      </DIV>
      {/section} 
   </DIV>
    <br />
    <br />
    <br/>
     {if $isShow == "T"}
    <div class="right_con_form">
      <form name="form_editbigtype" method="post" action="{util->baseUrl}/editknowledgetype.php?big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}" >
            <div style="width:100%; text-align:left; padding-top:5px; padding-left:50px">

                  大类名称：<input type="text" name="name" size="30" class="input" value="{$bigtype[0].name}"/><br /><br />
                  <input type="hidden" name="f" value="edit" /> 
                  <input type="hidden" name="id" value="{$bigtype[0].id}" /> 
                <input type="submit" value="更改" />&nbsp;&nbsp;<input type="button" onclick="resetv()" value="重置" />
            </div> 
      </form>  
    </div>
    {/if} </div>
</div>
<script language="javascript">
    function resetv(){ldelim}
    document.getElementById("name").value = "";
    {rdelim}
</script>