<link href="{util->baseUrl}/css/style.css" rel="stylesheet" type="text/css" />
<link href="{util->baseUrl}/css/reset.css" rel="stylesheet" type="text/css" />
<div id="con_right">
  <div class="right_con">
    <div class="right_con_bt">·{$smarty.get.big_type} < {$smarty.get.small_type}</div>
    <br />
    <br />
    <br />
    <DIV class="right_con_form">
      <form name="form_exportquestiontypes" method="post" action="">
          <div style="width:100%; text-align:center; padding-top:5px; padding-left:50px">
              <input type="submit" name="submit" value="导出试题">
          </div>
      </form>
    </DIV>
    <BR>
  </div>
</div>