<link href="{util->baseUrl}/css/style.css" rel="stylesheet" type="text/css" />
<link href="{util->baseUrl}/css/reset.css" rel="stylesheet" type="text/css" />
<SCRIPT src="{util->baseUrl}/Scripts/jquery.js"></SCRIPT>
<div id="con_right">
    <div class="right_con">
        <div class="right_con_bt">·{$smarty.get.big_type} < {$smarty.get.small_type}</div>
        <br />
        <br />
        <br />
        <DIV style="padding-left:56px; padding-top:56px;">
            <DIV style="padding-left:6px; ">
                <UL>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 18%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER:#21de26 1px solid;">序号</LI>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 18%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER:#21de26 1px solid;">模板名称</LI>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 18%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER:#21de26 1px solid;">分数线</LI>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 18%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER:#21de26 1px solid;">试题分布</LI>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 18%; FLOAT: left; text-align:center; HEIGHT: 25px; BORDER:#21de26 1px solid;">操作</LI>
                </UL>
            </DIV>
            {php} $i = 1;{/php}
            {section name=tID loop=$template}
            <DIV style="padding-left:6px; ">
                <UL>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 18%; FLOAT: left; text-align:center; HEIGHT: 73px; BORDER:#21de26 1px solid;">{php}echo $i;{/php}</LI>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 18%; FLOAT: left; text-align:center; HEIGHT: 73px; BORDER:#21de26 1px solid;">{$template[tID].name}</LI>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 18%; FLOAT: left; text-align:center; HEIGHT: 73px; BORDER:#21de26 1px solid;">{$template[tID].score}</LI>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 18%; FLOAT: left; text-align:center; HEIGHT: 73px; BORDER:#21de26 1px solid;">{$template[tID].type}</LI>
                    <LI style="LINE-HEIGHT: 23px; WIDTH: 18%; FLOAT: left; text-align:center; HEIGHT: 73px; BORDER:#21de26 1px solid;">
                        <a href="{util->baseUrl}/managetemplate.php?f=edit&id={$template[tID].id}&big_type={$smarty.get.big_type|escape:'hex'}&small_type={$smarty.get.small_type|escape:'hex'}">更改</a>&nbsp;<a href="javascript:if(window.confirm('确定删除？')==true){ldelim}window.location.href='{util->baseUrl}/managetemplate.php?f=del&id={$template[tID].id}&big_type={$smarty.get.big_type}&small_type={$smarty.get.small_type}';{rdelim}">删除</a>
                    </LI>
                </UL>
            </DIV>
            {php} $i++;{/php}
            {/section}
        </DIV>
        <BR>
        {if $isShow == "T"}
        <DIV class="right_con_form">
            <form name="form_templateupdate" method="post" action="" onsubmit="return chktemplate(this)">
                <div style="width:100%; text-align:left; padding-top:5px; padding-left:50px">

                    <br />
                    <br />
                    模板名称：<input type="text" id="templatename" name="templatename" size="30" class="input" value="{$temp.name}"/><br/><br/>
                    分数和分数线：
                    <select name="passscore">
                        <option value="">请选择</option>
                        {html_options options = $arrayScore selected = $temp.emattrid}
                    </select>
                    <br/>
                    <br/>
                    <DIV style="padding-left:6px; padding-top:26px;">
                        请输入题型个数（不填写代表0）<br/><br/>
                        {php} $i = 1;{/php}
                        {section name=tID loop=$tb_exam_type}
                        <DIV >
                            {assign var="kk" value=$tb_exam_type[tID].english}
                            {php} echo $i;{/php}、{$tb_exam_type[tID].chinese}:<input type="text" name="{$kk}num" value="{$temp.$kk}" class="input"/><br/><br/>
                        </DIV>
                        {php} $i++;{/php}
                        {/section}
                        <br/>
                        <br/>
                        <input type="hidden" name="f" value="edit" />
                        <input type="hidden" name="id" value="{$bigtype[0].id}" />
                        <input type="submit" name="updatetemp" value="更改" />
                    </div>
            </form>
        </DIV>
        {/if}
    </div>
</div>


<script language="javascript">
{literal}
    function chktemplate (form) {
        if (form.templatename.value == "") {
            alert("请输入模板名称！");
            form.templatename.focus();
            return false;
        }
        if (form.passscore.value == "") {
            alert("请选择分数线！");
            form.passscore.focus();
            return false;
        }
        $(":input[type=text][id!='templatename']").each(function(){
            if(isNaN(this.value)){
                alert("请输入数字！");
                this.focus();
                return false;
            }
        })
        return true;
    }
{/literal}
</script>